import { useContext } from "react";
import { BiDownArrowAlt } from "react-icons/bi";
import { MainContext } from "@/store";
import Head from "next/head";
import TodoList from "@/components/TodoList";
import styles from "@/scss/Home.module.scss";

export default function Home() {
  const { state, dispatch } = useContext(MainContext);

  return (
    <>
      <Head>
        <title>To-do list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {state.username ? (
          <>
            <h1 className={styles.title}>{state.username}'s To-do list</h1>
            <TodoList />
          </>
        ) : (
          <>
            <h1 className={styles.placeholder}>
              Please login to see your list
            </h1>
            <div className={styles.arrow}>
              <BiDownArrowAlt />
            </div>
          </>
        )}
      </main>
    </>
  );
}
