import { useReducer } from "react";
import { mainReducer } from "@/store/reducers";
import { MainContext, initialTodoList } from "@/store";
import Head from "next/head";
import TodoList from "@/components/TodoList";
import styles from "@/scss/Home.module.scss";

export default function Home() {
  const [state, dispatch] = useReducer(mainReducer, initialTodoList);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContext.Provider value={{ state, dispatch }}>
        <main>
          <h1 className={styles.title}>To-do list</h1>
          <TodoList />
        </main>
      </MainContext.Provider>
    </>
  );
}
