import { useContext } from "react";
import { MainContext } from "@/store";
import Head from "next/head";
import TodoList from "@/components/TodoList";
import styles from "@/scss/pages/Home.module.scss";

export default function Home() {
  const { state, dispatch } = useContext(MainContext);

  return (
    <>
      <Head>
        <title>To-do list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {state.username ? (
        <>
          <TodoList />
        </>
      ) : (
        <>
          <h1 className={styles.placeholder}>Please log in to see your list</h1>
        </>
      )}
    </>
  );
}
