import { useContext } from "react";
import { useRouter } from "next/router";
import { signInWithPopup } from "firebase/auth";
import { FcGoogle } from "react-icons/fc";
import { provider, auth } from "@/plugins/firebase";
import { MainContext } from "@/store";
import Head from "next/head";
import styles from "@/scss/pages/Login.module.scss";

export default function Login() {
  const onHandleSignIn = async () => {
    const res = await signInWithPopup(auth, provider);
    dispatch({
      type: "SET_USERNAME",
      payload: res.user.displayName,
    });
    return router.push("/");
  };

  const router = useRouter();
  const { state, dispatch } = useContext(MainContext);

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Login}>
        <h1 className={styles.title}>Sign in with Google</h1>
        <div
          onClick={onHandleSignIn}
          className={styles.googleSignIn}
          title="Log in with Google"
        >
          <span className={styles.icon}>
            <FcGoogle />
          </span>
          <span className={styles.text}>Log in</span>
        </div>
      </div>
    </>
  );
}
