import { useContext, useState } from "react";
import { useRouter } from "next/router";
import { MainContext } from "@/store";
import Head from "next/head";
import styles from "@/scss/pages/Login.module.scss";

export default function Login() {
  const router = useRouter();
  const { state, dispatch } = useContext(MainContext);
  const [usernameInput, setUsernameInput] = useState(state.username);

  const onHandleInput = (e) => setUsernameInput(e.target.value);

  const onHandleSubmit = (e) => {
    e.preventDefault();
    dispatch({
      type: "SET_USERNAME",
      payload: usernameInput,
    });
    router.push("/");
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Login}>
        <h1 className={styles.title}>Login</h1>
        <form className={styles.loginForm} onSubmit={onHandleSubmit}>
          <input
            type="text"
            className={styles.textInput}
            placeholder="Enter your username"
            value={usernameInput}
            onChange={onHandleInput}
          />
          <input type="submit" value="Login" className={styles.submitInput} />
        </form>
      </div>
    </>
  );
}
